-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVERAGE, 1) AS AVERAGE_DURATION
FROM (
SELECT CAR_ID, AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS AVERAGE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
) AS AV
WHERE AV.AVERAGE >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC