-- 코드를 입력하세요
WITH HISTORY AS (SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE, start_date)+1 AS DURATION, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = "트럭")

SELECT HISTORY_ID,
(CASE WHEN DURATION = 0 THEN DAILY_FEE
 WHEN (DURATION < 7 AND DURATION != 0) THEN DAILY_FEE * DURATION
    WHEN (DURATION >= 7 AND DURATION < 30) THEN FLOOR(DURATION * DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE LIKE "7%"))/100)
    WHEN (DURATION >= 30 AND DURATION < 90) THEN FLOOR(DURATION * DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE LIKE "30%"))/100)
    WHEN DURATION >= 90 THEN FLOOR(DURATION * DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE LIKE "90%"))/100)
 ELSE NULL
 END
 ) AS FEE
FROM HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC