-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, SUBSTRING(PUBLISHED_DATE, 1, 10) AS PUBLISHED_DATE
FROM AUTHOR AS A JOIN BOOK AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = "경제"
ORDER BY PUBLISHED_DATE